SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TODOS';

INSERT INTO TODOS
(
    TNO 
    ,TITLE
    ,DUEDATE 
    ,WRITER 
    ,ISDONE 
) 
VALUES 
(
    SEQ_TODOS.NEXTVAL
    ,'피자먹기'
    ,TO_DATE('2024-06-13 21:00:00', 'YYYY-MM-DD HH24:MI:SS')
    ,'홍길동'
    ,0
);

SELECT SEQ_TODOS.CURRVAL FROM DUAL;

SELECT * FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'SEQ_TODOS';

SELECT * FROM TODOS t WHERE TNO=1;

SELECT TNO
	 , TITLE
	 , DUEDATE	
	 , WRITER
	 , ISDONE 
	FROM PKNUSB.TODOS;

UPDATE TODOS SET
	TITLE  = '피자 두조각 먹기'
	,ISDONE = 1
WHERE TNO=1;

--DELETE FROM TODOS WHERE TNO=1;